config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
  resources :items, path: '/'
  resources :shopping_carts
  resources :orders
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :shopping_carts
  
  
  belongs_to :user, default: -> {Current.user}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :items
  belongs_to :users
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :items
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  validates :name_user, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :items
  has_many :orders
  has_many :shopping_cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user 
  before_action :protect_pages
    
    private
    def current_user
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def protect_pages
        redirect_to new_session_path unless Current.user
    end

    def authorize! (item)
        is_allowed = item.user_id == Current.user.id
        redirect_to item_path unless is_allowed
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :protect_pages, only: [:index, :show]
  

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    authorize! Item.find(params[:id])
  end

  def update
    authorize! Item.find(params[:id])
    if item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    authorize! item
  
    item.destroy

    redirect_to items_path
  end

  private
    def item_params
      params.require(:item).permit(:name, :description, :category, :price, :organization_id)
    end

    def item
      @item = Item.find(params[:item_id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :protect_pages
  
  def new
  end

  def create
    @user = User.find_by(name_user: params[:user_name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to items_path
    else  
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to items_path
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
    def create
        ShoppingCart.create(item_id: Item.find(params[:item_id]), user_id: Current.user.id) 
        redirect_to item_path(params[:item_id])
    end

    def index
        @shopping_cart= [ShoppingCart.where(user_id: Current.user)]
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :protect_pages
  
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to new_session_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name_user, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<h1>Editar Articulo</h1>

<%= form_with model: @item do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/index.html.erb
<h1>Articulos</h1>
<h2>
 <%=link_to 'crear articulo', new_item_path if Current.user%>
 <%= link_to 'login', new_session_path unless Current.user %>
 <%= link_to 'register', new_user_path unless Current.user %>
 <%=link_to 'Shopping Cart', shopping_carts_url if Current.user%>
 <%= link_to 'logout', session_path(Current.user), method: :delete if Current.user %>
</h2>
<ul>
  <% @items.each do |item| %>
    <li>
        <%=link_to item.name, item %>
    </li>
    
    <li>
      <%= item.price%>
    </li>
  <% end %>
</ul>




  

app/views/items/new.html.erb
<h1>Nuevo Articulo</h1>

<%= form_with model: @item do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<p><%= @item.description %></p>

<h2><%= @item.price %></h2>

<%= link_to "Editar", edit_item_path(@item) if @item.user == Current.user %>
<%= link_to 'Eliminar', item_path(@item), method: :delete if @item.user == Current.user%>

<%= link_to'Add Shopping Carts', shopping_carts_url(item_id: @item.id),method: :post if @item.user == Current.user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
  <%= f.label :name_user %>
  <%= f.text_field :name_user, placeholder: "Username" %>
  </div>
  <div>
  <%= f.label :email %>
  <%= f.text_field :email, placeholder: "E-mail" %>
  <div>
  <%= f.label :role %>
  <%= f.select :role, [["Cliente", "costomer"], ["Tienda", "organization"]] %>
  </div>
  <div>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div>
  <%= f.submit "Create Account" %>
  </div>
<% end %>